### ISSUE TITLE
New Features

### ISSUE THREAD

**Issue by war12542715712** [Baseult/Baseult-Rev-League-of-Legends-Lobby-Revealer#1]
Looks good but is there a way u could add 2 things, a way to know which summoner is corresponding Ally and instead of u.gg, op.gg.
Thanks

**Comment by proddeha** [comment]
Hey! i just wanted to ask cuz im new to github, how can i exactly make it run.. i would appreciate any help!

**Comment by war12542715712** [comment]
> Hey! i just wanted to ask cuz im new to github, how can i exactly make it run.. i would appreciate any help!

Here u go, https://www.unknowncheats.me/forum/downloads.php?do=file&id=38604

**Comment by d0lph1nman** [comment]
> Hey! i just wanted to ask cuz im new to github, how can i exactly make it run.. i would appreciate any help!

Download Visual Studio and open the solution. 2 errors I got when trying to build the solution was a package not being found and a file was blocked by Microsoft defender. Both a simple fix if you just google the error.

And if you want to use op.gg instead of u.gg just open the output log and it outputs all 5 summoner names for you to copy paste into op.gg. Or you can use just implement it yourself in the solution since all the code is there.

Thank you Baseult for this flawless tool!

**Comment by daedaluxs** [comment]
Yo, whats your discord? Links don't work. :(

**Comment by Baseult** [comment]
closed
